### ISSUE TITLE
Phone number input enhancements

### ISSUE THREAD

**Issue by Mihails-Simvulidi** [keepalivedev/KeepAlive#24]
It would be nice if it was possible to choose a phone number for SMS/call from contacts. Currently I'm only able to enter a phone number of SMS/call recipient by hand or by pasting it from another app.

Also, when I paste a phone number from contacts, I can't save it until I remove all spaces from it. Couldn't it be done automatically upon save?

**Comment by keepalivedev** [comment]
I have considered doing that but, given the number of sensitive permissions the app already has to request just to function, I didn't want to add any more than was necessary for fear of scaring away users.  Those fears could be unfounded though...

I wasn't thinking about copy/paste, that would definitely be possible.  I will look into removing invalid characters from the input automatically.

**Comment by keepalivedev** [comment]
The copy/paste change is in the 1.1.4 release.
