### ISSUE TITLE
feature req: multiple sms numbers to send message to

### ISSUE THREAD

**Issue by nutpantz** [keepalivedev/KeepAlive#26]
It would be great if there were multiple numbers to send the emergency sms alert to. (The alert message could be the same i would think)

3 different numbers maximum may be enough for most people, but elderly people might benefit from more like 5.

**Comment by nutpantz** [comment]
Seems that you can. I would never have known if i did not mistakenly click the button and think i had to add the info again.

**Comment by keepalivedev** [comment]
I agree that the UI doesn't specifically indicate that you can add multiple SMS contacts however it is mentioned in the features list.   I'd prefer to keep it as is for now.  Thank you for the feedback!
