### ISSUE TITLE
feature req: test text without monitoring active

### ISSUE THREAD

**Issue by nutpantz** [keepalivedev/KeepAlive#27]
It would be nice if the test message sending was available without having to turn on monitoring. And it would be nice if there was a confirmation dialog before sending.

Or at least a greyed out"send test" until all permissions are given.

**Comment by keepalivedev** [comment]
You should be able to use the Test Alert SMS when monitoring is disabled as long as there is at least one SMS emergency contact.  If that doesn't seem to be the case can you send me a screenshot of what the home page looks like?

**Comment by keepalivedev** [comment]
Well, without a contact, who is it going to send the test alert to?  Or do you mean the button should always be visible, but greyed out if it can't be used?

**Comment by nutpantz** [comment]
Yes i mean the button should be always visible and greyed out if it can't be used.

**Comment by keepalivedev** [comment]
This change is included in release 1.1.4.
