### ISSUE TITLE
gps location acquired, monitoring disabled.

### ISSUE THREAD

**Issue by nutpantz** [keepalivedev/KeepAlive#47]
**Describe the bug**
gps location was acquired while monitoring is disabled.

**Expected behavior**
while monitoring is disabled the app should be disabled.

**Screenshots**

**Smartphone (please complete the following information):**
 - Device:pixel 6
 - OS:  Android 12
 - App Version: 1.1.3

**Additional context**
app has been disabled for days, and just today i got a notification that the gps location was acquired by the app.

**Comment by keepalivedev** [comment]
This should be basically impossible in 1.1.3, location is only obtained when an alert is triggered and it checks whether the app is enabled before sending an alert.

When you say notification, do you mean an Android Notification from Keep Alive?  Or one of those 'Toast' messages that show up near the bottom of the screen?

Any chance you can upload the app logs?  Or if you go into Settings > Apps > Keep Alive > Permissions, does it say 'last accessed at' under the Location permission?  I am wondering if location had been previously accessed while sending a test alert and it was just now showing the notification...

**Comment by nutpantz** [comment]
Yes it was a Android notification the the notification area. There is nothing in the app log now and nothing in the last accessed area.
All tests of the app and sms were done on a different phone, i don't think i sent a test alert from my pixel and if i did it was over a week ago and at least one reboot.
However anything is possible. I don't think my battery is being used any more then normal.

I'll keep an eye on in an report of it happens again. And i make sure to get any logs then.

**Comment by nutpantz** [comment]
2024-03-16 13:15:01: No alarm found or monitoring is disabled
2024-03-16 13:15:01: Have all permissions
2024-03-16 13:15:01: KeepAlive starting up!


Happened again just noticed it in my notification area when i was looking at my phone this morning.

Nothing in logs.. (the time in logs is universal time?)

**Comment by nutpantz** [comment]
and again. it seems it gets the location in the background when i am using the gps.
even if monitoring is turned off.

**Comment by p-doyle** [comment]
Did you see the location check after unlocking or waking up your device?  I am seeing an issue now where an alert will trigger and the initial SMS will be sent, but for some reason the OS delays the attempt to get the location until the device fully wakes back up.

**Comment by keepalivedev** [comment]
Did you see the location check after unlocking or waking up your device? I am seeing an issue now where an alert will trigger and the initial SMS will be sent, but for some reason the OS delays the attempt to get the location until the device fully wakes back up.

**Comment by nutpantz** [comment]
Yes, the two times of happened I saw it first thing in the morning when going to check my email
