### ISSUE TITLE
Minor improvement screenshots

### ISSUE THREAD

**Issue by PanderMusubi** [keepalivedev/KeepAlive#5]
A minor improvement for the screenshots is to crop the decoration, i.e. the header and footer with time, notifications and launchers. This is recommended for Fastlane, F-Droid, etc.

Additionally, run `optipng` on the result of the cropping to minimalize the PNG files without loosing quality.

**Comment by keepalivedev** [comment]
Thanks for the suggestion.  I made the changes under PR https://github.com/keepalivedev/KeepAlive/pull/7

**Comment by PanderMusubi** [comment]
They look good. Thanks.
