### ISSUE TITLE
Save debug logs on device

### ISSUE THREAD

**Issue by Mihails-Simvulidi** [keepalivedev/KeepAlive#51]
**Is your feature request related to a problem? Please describe.**
When I open the KeepAlive app and go to Debug Logs, I only see last minute records. If I remove the app from recents and reopen, previous logs aren't present, so it seems that they are only stored in RAM. So I can't verify that the app is actually checking activity every few hours.

**Describe the solution you'd like**
Save debug logs on device and keep for at least one week.

**Describe alternatives you've considered**
None.

**Additional context**
![image](https://github.com/keepalivedev/KeepAlive/assets/52172784/a0a572c4-9f99-4ece-87a3-028b618ef1d2)

**Comment by keepalivedev** [comment]
As of 1.2.0 the last 1000 log entries are saved to disk.

**Comment by Mihails-Simvulidi** [comment]
Thank you very much, it works for me!
