### ISSUE TITLE
F-Droid can't build

### ISSUE THREAD

**Issue by licaon-kter** [keepalivedev/KeepAlive#66]
ref: https://monitor.f-droid.org/builds/log/io.keepalive.android/120#site-footer

diff log: [keep120.log](https://github.com/user-attachments/files/16071152/keep120.log)

/LE: fyi https://gitlab.com/fdroid/fdroiddata/-/commit/b7592d68c5e50897a8bf9603cb795229a28c40bd

**Comment by keepalivedev** [comment]
I updated the release binary, is there a way to remove the disable flag or do I have to publish a new version?

**Comment by licaon-kter** [comment]
Will have to test locally first, asap

**Comment by licaon-kter** [comment]
that does it: https://gitlab.com/fdroid/fdroiddata/-/commit/4694f1a350685b408af860aa47857a66141d5d14 :tada: 

what did you do differently @keepalivedev  ?

**Comment by keepalivedev** [comment]
Thanks!  It seems I had some minor changes in my local version when I built the release and had forgotten that Fdroid verifies the release binary, sorry for the hassle!

**Comment by linsui** [comment]
Reproducible build failed again. The diff is large. Was your apk built from the tag?

**Comment by keepalivedev** [comment]
I am not sure what happened this time, I didn't have any local changes when I built it.  

I just downloaded the release zip and rebuilt it using that and updated the release binaries.  Moving forward I'll make sure to do that instead of using my working project folder.  I apologize for the trouble.

**Comment by linsui** [comment]
It's still not reprodcible and the diff is large... Did you update the jdk? Or maybe you need to clean the cache and rebuild? How did you build the apk? With command line or Android Studio?

**Comment by keepalivedev** [comment]
I've been building with Android Studio.  I think the issue may have been from changing the java runtime in Android Studio to one that included JCEF in an attempt to fix a separate problem I was having.  I changed it back to the default and updated the release APK, can you let me know if that works?   And is there a better way I should be doing this?  Thank you!

**Comment by linsui** [comment]
The diff is even larger... Is it still built from the same commit?

**Comment by keepalivedev** [comment]
Yes, the last two attempts I downloaded the source zip from the release and built using that.

**Comment by linsui** [comment]
Can you rebuild the apk with `gradle clean assembleFDroidRelease`? And please make sure the jdk is 17. I have no idea why the diff is so large...

**Comment by keepalivedev** [comment]
Android Studio is set to use Java 17.0.11.  I am on windows and tried using gradlew but get an error 'Could not resolve com.android.tools.build:gradle:8.6.0.'. Building with Android Studio works fine though so it must be doing something different. I am going to setup a Linux machine and try to build it from there using the command line.

**Comment by linsui** [comment]
Hmmm, I thought it should also be reproducible to build a pure kotlin app on Windows. The diff is so large that I thought we must missed something here.

**Comment by keepalivedev** [comment]
All of the previous releases have been built on Windows.  The only thing build related that changed from the last release is I updated the gradle version in graddle-wrapper.properties and the plugin versions in the project build.gradle.

**Comment by keepalivedev** [comment]
I was able to build it from the command line on Linux without any errors and updated the release APK again... can you let me know if that one looks any better?

**Comment by linsui** [comment]
Yes, it's better... But why? I'm confused. The old versions were built on windows and have no problem. What should we do now?

**Comment by keepalivedev** [comment]
It's better but it still doesn't match?

**Comment by linsui** [comment]
It matches. :) But I guess it's not convenient for you to create releases from linux? You can do that with GHA of course.

**Comment by keepalivedev** [comment]
It is not hard to do but like you said shouldn't be necessary.  Now that I know I can build the correct version from Linux I can do some more troubleshooting on my end to figure out what is wrong with the Windows build.  I really appreciate your help and am sorry for the trouble!  And I hadn't considered using a Github Action, that would definitely make this easier, my only concern would be how to keep the app signing key safe.
