### ISSUE TITLE
Emphasize when alert SMS is a test

### ISSUE THREAD

**Issue by PanderMusubi** [keepalivedev/KeepAlive#67]
**Is your feature request related to a problem? Please describe.**
When using the TEST ALERT SMS functionality, it is not indicated to the receivers that it concerns a test, which might be discomforting or alarming to those people.

**Describe the solution you'd like**
Before sending the SMS messages, send an SMS message with the text:

    The following messages are a test from the Keep Alive app.

and after the SMS messages, send an SMS message with the text:

    This is the end of the test from the Keep Alive app.

**Describe alternatives you've considered**
Inform the receiver in another way that you are about to use the test functionality of this app.

**Additional context**
Do not add the info about the test inside the SMS messages that are being sent in order not to pollute those or to go over the maximum number of characters for fine-tunes messages, but use a separate message before and a separate message after as described above.

**Comment by keepalivedev** [comment]
I like the idea, my only concern would be the extra SMS being sent.  I would need to add a dialogue to explain to the user that it would be sending an additional 2 SMS, or maybe give them the option to send the warnings?

**Comment by PanderMusubi** [comment]
I think it prevents unneeded chaos and the costs of the extra SMS are worth it.

**Comment by keepalivedev** [comment]
This is what I am thinking.  Do you think the 2nd SMS is necessary or would it be enough to just have a warning message sent first?
![image](https://github.com/user-attachments/assets/3de8604d-4c68-4bd5-b7e2-4b37cfd98758)

**Comment by keepalivedev** [comment]
This is now available in [1.3.0](https://github.com/keepalivedev/KeepAlive/releases/tag/1.3.0). It should be on Google Play in a few days and F-Droid in a week or two. Please try it out and let me know how it goes.
