### ISSUE TITLE
Add webhook

### ISSUE THREAD

**Issue by thejeshgn** [keepalivedev/KeepAlive#68]
Its a new feature, along with call and sms add sending notification through standard webhook.

This allows to add logic and routing on the server side. Specially useful to integrate with other systems like HomeAssistant.

**Comment by keepalivedev** [comment]
I will look into adding this.  My only hesitation is that this will require the addition of the INTERNET permission as well as potentially requiring new disclosures in the Google Play Store since this will be considered transmitting data to a 3rd party, even if the 3rd party is technically being configured by the user...

**Comment by thejeshgn** [comment]
I understand but it will be a great feature, do think about it.

**Comment by keepalivedev** [comment]
Will this be enough configuration options?
![image](https://github.com/user-attachments/assets/67778ff9-9411-4f3c-8288-4b7d3461b16e)

**Comment by thejeshgn** [comment]
Looks good will the body be empty and all the details are sent via query parameters?

**Comment by keepalivedev** [comment]
I was thinking of adding an option for whether to include the location as either query parameters, in the body as JSON or in the body as form fields.  Would that work?

**Comment by thejeshgn** [comment]
Yes, that works.

if GET then query params.
if POST then body
works.

**Comment by keepalivedev** [comment]
> 1. Looks good will the body be empty and all the details are sent via query parameters?
> 2. I am guessing mobile_number, lat, lon and message are part of parameters.

The way it is currently set up, there is only one webhook trigger and its not tied to the SMS contacts, so by default it will just send a request to the configured URL.  If you wanted to include a message it would need to be as a query parameter on the URL.  Location can be included in either the body or as additional query parameters.  I haven't implemented it yet but I was thinking "lat", "lon" and "acc" for the GPS coords and then if it was able to geocode the coords it would be under "address".

**Comment by thejeshgn** [comment]
Sounds good. Thank you.

**Comment by keepalivedev** [comment]
This is now available in [1.3.0](https://github.com/keepalivedev/KeepAlive/releases/tag/1.3.0).  It should be on Google Play in a few days and F-Droid in a week or two.  Please try it out and let me know how it goes.
